version: '3.8'

services:
  database:
    container_name: cilist-db
    image: rumi87/cilist-db:${GIT_COMMIT_SHORT}
  
  backend:
    image: rumi/cilist-db:${GIT_COMMIT_SHORT}
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - BASE_URL_PORT=5000
      - MYSQL_ROOT_PASSWORD=s3k0l4hd3v0p5
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=59W5jcf4RrEVjfqDAY9xVA_2
      - DATABASE_DATABASE=dbcilist
      - DATABASE_HOST=db-cilist.cjzc7lrtq759.ap-southeast-1.rds.amazonaws.com
      - DATABASE_PORT=3306
    
  frontend:
    image: rumi87/cilist-fe:${GIT_COMMIT_SHORT}
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://api.rumi.local
