# Service untuk frontend
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: devops-rumi
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
